export default {
    LOGIN: 'LOG IN',
    REGISTER: 'REGISTER',
    FACEBOOK_LOG_IN: "Continue with Facebook",
    GOOGLE_LOG_IN: "Sign in with Google",
    LOGOUT: 'LOG OUT',
    EMAIL_PLACEHOLDER: 'Enter your email',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    EMAIL_REGISTER_PLACEHOLDER: 'Email *',
    PASSWORD_REGISTER_PLACEHOLDER: 'Password *',
    RE_PASSWORD_REGISTER_PLACE_HOLDER: 'Re-password *',
    FIRST_NAME_REGISTER: 'First Name',
    LAST_NAME_REGISTER: 'Last Name',
    PHONE_REGISTER: 'Phone right',
    ADDRESS_REGISTER: 'Address',
    BASE_PATH: "http://yourshares.tk/",
    FACEBOOK_APP_ID: '2475267839196769',
    GOOGLE_ANDROID_APP_ID: '754455661839-524tf6ge17bpc5688ilp7boo6focic8t.apps.googleusercontent.com',
    GOOGLE_IOS_APP_ID: '754455661839-et0kfpkkh4g4530dvp6j5hcs1uj3l6hb.apps.googleusercontent.com'
};